/**
 * Complete list of world countries with ISO 3166-1 alpha-2 codes
 * Sorted alphabetically by Hungarian name, with Hungary first
 */

export interface Country {
  code: string;
  name: string;
  nameEn: string;
}

export const COUNTRIES: Country[] = [
  // Hungary first (priority)
  { code: 'HU', name: 'Magyarorszag', nameEn: 'Hungary' },

  // Neighboring countries (priority)
  { code: 'AT', name: 'Ausztria', nameEn: 'Austria' },
  { code: 'HR', name: 'Horvatorszag', nameEn: 'Croatia' },
  { code: 'RO', name: 'Romania', nameEn: 'Romania' },
  { code: 'RS', name: 'Szerbia', nameEn: 'Serbia' },
  { code: 'SK', name: 'Szlovakia', nameEn: 'Slovakia' },
  { code: 'SI', name: 'Szlovenia', nameEn: 'Slovenia' },
  { code: 'UA', name: 'Ukrajna', nameEn: 'Ukraine' },

  // EU countries (alphabetically by Hungarian name)
  { code: 'BE', name: 'Belgium', nameEn: 'Belgium' },
  { code: 'BG', name: 'Bulgaria', nameEn: 'Bulgaria' },
  { code: 'CY', name: 'Ciprus', nameEn: 'Cyprus' },
  { code: 'CZ', name: 'Csehorszag', nameEn: 'Czech Republic' },
  { code: 'DK', name: 'Dania', nameEn: 'Denmark' },
  { code: 'EE', name: 'Esztorszag', nameEn: 'Estonia' },
  { code: 'FI', name: 'Finnorszag', nameEn: 'Finland' },
  { code: 'FR', name: 'Franciaorszag', nameEn: 'France' },
  { code: 'GR', name: 'Gorogorszag', nameEn: 'Greece' },
  { code: 'NL', name: 'Hollandia', nameEn: 'Netherlands' },
  { code: 'IE', name: 'Irorszag', nameEn: 'Ireland' },
  { code: 'PL', name: 'Lengyelorszag', nameEn: 'Poland' },
  { code: 'LV', name: 'Lettorszag', nameEn: 'Latvia' },
  { code: 'LT', name: 'Litvania', nameEn: 'Lithuania' },
  { code: 'LU', name: 'Luxemburg', nameEn: 'Luxembourg' },
  { code: 'MT', name: 'Malta', nameEn: 'Malta' },
  { code: 'DE', name: 'Nemetorszag', nameEn: 'Germany' },
  { code: 'IT', name: 'Olaszorszag', nameEn: 'Italy' },
  { code: 'PT', name: 'Portugalia', nameEn: 'Portugal' },
  { code: 'ES', name: 'Spanyolorszag', nameEn: 'Spain' },
  { code: 'SE', name: 'Svedorszag', nameEn: 'Sweden' },

  // Other European countries
  { code: 'AL', name: 'Albania', nameEn: 'Albania' },
  { code: 'AD', name: 'Andorra', nameEn: 'Andorra' },
  { code: 'BY', name: 'Belarusz', nameEn: 'Belarus' },
  { code: 'BA', name: 'Bosznia-Hercegovina', nameEn: 'Bosnia and Herzegovina' },
  { code: 'GB', name: 'Egyesult Kiralysag', nameEn: 'United Kingdom' },
  { code: 'IS', name: 'Izland', nameEn: 'Iceland' },
  { code: 'XK', name: 'Koszovo', nameEn: 'Kosovo' },
  { code: 'LI', name: 'Liechtenstein', nameEn: 'Liechtenstein' },
  { code: 'MK', name: 'Eszak-Macedonia', nameEn: 'North Macedonia' },
  { code: 'MD', name: 'Moldova', nameEn: 'Moldova' },
  { code: 'MC', name: 'Monaco', nameEn: 'Monaco' },
  { code: 'ME', name: 'Montenegro', nameEn: 'Montenegro' },
  { code: 'NO', name: 'Norvegia', nameEn: 'Norway' },
  { code: 'RU', name: 'Oroszorszag', nameEn: 'Russia' },
  { code: 'SM', name: 'San Marino', nameEn: 'San Marino' },
  { code: 'CH', name: 'Svajc', nameEn: 'Switzerland' },
  { code: 'VA', name: 'Vatikan', nameEn: 'Vatican City' },

  // Rest of the world (alphabetically by Hungarian name)
  { code: 'AF', name: 'Afganisztan', nameEn: 'Afghanistan' },
  { code: 'DZ', name: 'Algiria', nameEn: 'Algeria' },
  { code: 'US', name: 'Amerikai Egyesult Allamok', nameEn: 'United States' },
  { code: 'AO', name: 'Angola', nameEn: 'Angola' },
  { code: 'AG', name: 'Antigua es Barbuda', nameEn: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina', nameEn: 'Argentina' },
  { code: 'AU', name: 'Ausztralia', nameEn: 'Australia' },
  { code: 'AZ', name: 'Azerbajdzsan', nameEn: 'Azerbaijan' },
  { code: 'BS', name: 'Bahama-szigetek', nameEn: 'Bahamas' },
  { code: 'BH', name: 'Bahrein', nameEn: 'Bahrain' },
  { code: 'BD', name: 'Banglades', nameEn: 'Bangladesh' },
  { code: 'BB', name: 'Barbados', nameEn: 'Barbados' },
  { code: 'BZ', name: 'Belize', nameEn: 'Belize' },
  { code: 'BJ', name: 'Benin', nameEn: 'Benin' },
  { code: 'BT', name: 'Bhutan', nameEn: 'Bhutan' },
  { code: 'BO', name: 'Bolivia', nameEn: 'Bolivia' },
  { code: 'BW', name: 'Botswana', nameEn: 'Botswana' },
  { code: 'BR', name: 'Brazilia', nameEn: 'Brazil' },
  { code: 'BN', name: 'Brunei', nameEn: 'Brunei' },
  { code: 'BF', name: 'Burkina Faso', nameEn: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi', nameEn: 'Burundi' },
  { code: 'CL', name: 'Chile', nameEn: 'Chile' },
  { code: 'CO', name: 'Kolumbia', nameEn: 'Colombia' },
  { code: 'KM', name: 'Comore-szigetek', nameEn: 'Comoros' },
  { code: 'CR', name: 'Costa Rica', nameEn: 'Costa Rica' },
  { code: 'TD', name: 'Csad', nameEn: 'Chad' },
  { code: 'ZA', name: 'Del-Afrika', nameEn: 'South Africa' },
  { code: 'SS', name: 'Del-Szudan', nameEn: 'South Sudan' },
  { code: 'KR', name: 'Del-Korea', nameEn: 'South Korea' },
  { code: 'DM', name: 'Dominika', nameEn: 'Dominica' },
  { code: 'DO', name: 'Dominikai Koztarsasag', nameEn: 'Dominican Republic' },
  { code: 'DJ', name: 'Dzsibuti', nameEn: 'Djibouti' },
  { code: 'EC', name: 'Ecuador', nameEn: 'Ecuador' },
  { code: 'GQ', name: 'Egyenlitoi-Guinea', nameEn: 'Equatorial Guinea' },
  { code: 'AE', name: 'Egyesult Arab Emirsegek', nameEn: 'United Arab Emirates' },
  { code: 'EG', name: 'Egyiptom', nameEn: 'Egypt' },
  { code: 'CI', name: 'Elefantcsontpart', nameEn: 'Ivory Coast' },
  { code: 'ER', name: 'Eritrea', nameEn: 'Eritrea' },
  { code: 'ET', name: 'Etiopia', nameEn: 'Ethiopia' },
  { code: 'FJ', name: 'Fidzsi', nameEn: 'Fiji' },
  { code: 'PH', name: 'Fulop-szigetek', nameEn: 'Philippines' },
  { code: 'GA', name: 'Gabon', nameEn: 'Gabon' },
  { code: 'GM', name: 'Gambia', nameEn: 'Gambia' },
  { code: 'GH', name: 'Ghana', nameEn: 'Ghana' },
  { code: 'GD', name: 'Grenada', nameEn: 'Grenada' },
  { code: 'GE', name: 'Gruzia', nameEn: 'Georgia' },
  { code: 'GT', name: 'Guatemala', nameEn: 'Guatemala' },
  { code: 'GN', name: 'Guinea', nameEn: 'Guinea' },
  { code: 'GW', name: 'Bissau-Guinea', nameEn: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana', nameEn: 'Guyana' },
  { code: 'HT', name: 'Haiti', nameEn: 'Haiti' },
  { code: 'HN', name: 'Honduras', nameEn: 'Honduras' },
  { code: 'IN', name: 'India', nameEn: 'India' },
  { code: 'ID', name: 'Indonezia', nameEn: 'Indonesia' },
  { code: 'IQ', name: 'Irak', nameEn: 'Iraq' },
  { code: 'IR', name: 'Iran', nameEn: 'Iran' },
  { code: 'IL', name: 'Izrael', nameEn: 'Israel' },
  { code: 'JM', name: 'Jamaica', nameEn: 'Jamaica' },
  { code: 'JP', name: 'Japan', nameEn: 'Japan' },
  { code: 'YE', name: 'Jemen', nameEn: 'Yemen' },
  { code: 'JO', name: 'Jordania', nameEn: 'Jordan' },
  { code: 'CM', name: 'Kamerun', nameEn: 'Cameroon' },
  { code: 'CA', name: 'Kanada', nameEn: 'Canada' },
  { code: 'QA', name: 'Katar', nameEn: 'Qatar' },
  { code: 'KZ', name: 'Kazahsztan', nameEn: 'Kazakhstan' },
  { code: 'TL', name: 'Kelet-Timor', nameEn: 'East Timor' },
  { code: 'KE', name: 'Kenya', nameEn: 'Kenya' },
  { code: 'CN', name: 'Kina', nameEn: 'China' },
  { code: 'KG', name: 'Kirgizisztan', nameEn: 'Kyrgyzstan' },
  { code: 'KI', name: 'Kiribati', nameEn: 'Kiribati' },
  { code: 'CG', name: 'Kongoi Koztarsasag', nameEn: 'Republic of the Congo' },
  { code: 'CD', name: 'Kongoi Dem. Koztarsasag', nameEn: 'Democratic Republic of the Congo' },
  { code: 'CU', name: 'Kuba', nameEn: 'Cuba' },
  { code: 'KW', name: 'Kuvait', nameEn: 'Kuwait' },
  { code: 'LA', name: 'Laosz', nameEn: 'Laos' },
  { code: 'LS', name: 'Lesotho', nameEn: 'Lesotho' },
  { code: 'LB', name: 'Libanon', nameEn: 'Lebanon' },
  { code: 'LR', name: 'Liberia', nameEn: 'Liberia' },
  { code: 'LY', name: 'Libia', nameEn: 'Libya' },
  { code: 'MG', name: 'Madagaszkar', nameEn: 'Madagascar' },
  { code: 'MY', name: 'Malajzia', nameEn: 'Malaysia' },
  { code: 'MW', name: 'Malawi', nameEn: 'Malawi' },
  { code: 'MV', name: 'Maldiv-szigetek', nameEn: 'Maldives' },
  { code: 'ML', name: 'Mali', nameEn: 'Mali' },
  { code: 'MA', name: 'Marokko', nameEn: 'Morocco' },
  { code: 'MH', name: 'Marshall-szigetek', nameEn: 'Marshall Islands' },
  { code: 'MR', name: 'Mauritania', nameEn: 'Mauritania' },
  { code: 'MU', name: 'Mauritius', nameEn: 'Mauritius' },
  { code: 'MX', name: 'Mexiko', nameEn: 'Mexico' },
  { code: 'MM', name: 'Mianmar', nameEn: 'Myanmar' },
  { code: 'FM', name: 'Mikronezia', nameEn: 'Micronesia' },
  { code: 'MN', name: 'Mongolia', nameEn: 'Mongolia' },
  { code: 'MZ', name: 'Mozambik', nameEn: 'Mozambique' },
  { code: 'NA', name: 'Namibia', nameEn: 'Namibia' },
  { code: 'NR', name: 'Nauru', nameEn: 'Nauru' },
  { code: 'NP', name: 'Nepal', nameEn: 'Nepal' },
  { code: 'NI', name: 'Nicaragua', nameEn: 'Nicaragua' },
  { code: 'NE', name: 'Niger', nameEn: 'Niger' },
  { code: 'NG', name: 'Nigeria', nameEn: 'Nigeria' },
  { code: 'KP', name: 'Eszak-Korea', nameEn: 'North Korea' },
  { code: 'OM', name: 'Oman', nameEn: 'Oman' },
  { code: 'PK', name: 'Pakisztan', nameEn: 'Pakistan' },
  { code: 'PW', name: 'Palau', nameEn: 'Palau' },
  { code: 'PS', name: 'Palesztina', nameEn: 'Palestine' },
  { code: 'PA', name: 'Panama', nameEn: 'Panama' },
  { code: 'PG', name: 'Papua Uj-Guinea', nameEn: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay', nameEn: 'Paraguay' },
  { code: 'PE', name: 'Peru', nameEn: 'Peru' },
  { code: 'RW', name: 'Ruanda', nameEn: 'Rwanda' },
  { code: 'KN', name: 'Saint Kitts es Nevis', nameEn: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia', nameEn: 'Saint Lucia' },
  { code: 'VC', name: 'Saint Vincent es Grenadine', nameEn: 'Saint Vincent and the Grenadines' },
  { code: 'SB', name: 'Salamon-szigetek', nameEn: 'Solomon Islands' },
  { code: 'SV', name: 'Salvador', nameEn: 'El Salvador' },
  { code: 'WS', name: 'Szamoa', nameEn: 'Samoa' },
  { code: 'ST', name: 'Sao Tome es Principe', nameEn: 'Sao Tome and Principe' },
  { code: 'SA', name: 'Szaud-Arabia', nameEn: 'Saudi Arabia' },
  { code: 'SC', name: 'Seychelle-szigetek', nameEn: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone', nameEn: 'Sierra Leone' },
  { code: 'SG', name: 'Szingapur', nameEn: 'Singapore' },
  { code: 'SO', name: 'Szomalia', nameEn: 'Somalia' },
  { code: 'LK', name: 'Sri Lanka', nameEn: 'Sri Lanka' },
  { code: 'SR', name: 'Suriname', nameEn: 'Suriname' },
  { code: 'SZ', name: 'Szvazifolde', nameEn: 'Eswatini' },
  { code: 'SD', name: 'Szudan', nameEn: 'Sudan' },
  { code: 'SY', name: 'Sziria', nameEn: 'Syria' },
  { code: 'TJ', name: 'Tadzsikisztan', nameEn: 'Tajikistan' },
  { code: 'TW', name: 'Tajvan', nameEn: 'Taiwan' },
  { code: 'TZ', name: 'Tanzania', nameEn: 'Tanzania' },
  { code: 'TH', name: 'Thaifold', nameEn: 'Thailand' },
  { code: 'TG', name: 'Togo', nameEn: 'Togo' },
  { code: 'TO', name: 'Tonga', nameEn: 'Tonga' },
  { code: 'TT', name: 'Trinidad es Tobago', nameEn: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunézia', nameEn: 'Tunisia' },
  { code: 'TR', name: 'Torokorszag', nameEn: 'Turkey' },
  { code: 'TM', name: 'Turkmenisztan', nameEn: 'Turkmenistan' },
  { code: 'TV', name: 'Tuvalu', nameEn: 'Tuvalu' },
  { code: 'UG', name: 'Uganda', nameEn: 'Uganda' },
  { code: 'NZ', name: 'Uj-Zeland', nameEn: 'New Zealand' },
  { code: 'UY', name: 'Uruguay', nameEn: 'Uruguay' },
  { code: 'UZ', name: 'Uzbegisztan', nameEn: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu', nameEn: 'Vanuatu' },
  { code: 'VE', name: 'Venezuela', nameEn: 'Venezuela' },
  { code: 'VN', name: 'Vietnam', nameEn: 'Vietnam' },
  { code: 'ZM', name: 'Zambia', nameEn: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe', nameEn: 'Zimbabwe' },
  { code: 'CV', name: 'Zold-foki Koztarsasag', nameEn: 'Cape Verde' },
  { code: 'CF', name: 'Kozep-afrikai Koztarsasag', nameEn: 'Central African Republic' },
  { code: 'AM', name: 'Ormenyorszag', nameEn: 'Armenia' },
];

// EU countries only
export const EU_COUNTRIES = COUNTRIES.filter(c =>
  ['AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR',
   'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'MT', 'NL', 'PL', 'PT', 'RO',
   'SE', 'SI', 'SK'].includes(c.code)
);

// Neighboring countries of Hungary
export const NEIGHBORING_COUNTRIES = COUNTRIES.filter(c =>
  ['HU', 'AT', 'SK', 'UA', 'RO', 'RS', 'HR', 'SI'].includes(c.code)
);

// Get country by code
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code);
}

// Get country name by code
export function getCountryName(code: string): string {
  const country = getCountryByCode(code);
  return country?.name || code;
}
