-- Add new AuditAction enum values for security events
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN_SUCCESS';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGOUT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET_REQUEST';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET_COMPLETE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SESSION_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SESSION_EXPIRED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RATE_LIMITED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PERMISSION_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DELETE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPORT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IMPORT';

-- Add new ActorType enum values
ALTER TYPE "ActorType" ADD VALUE IF NOT EXISTS 'OPERATOR';
ALTER TYPE "ActorType" ADD VALUE IF NOT EXISTS 'PARTNER';
ALTER TYPE "ActorType" ADD VALUE IF NOT EXISTS 'NETWORK_ADMIN';
ALTER TYPE "ActorType" ADD VALUE IF NOT EXISTS 'PLATFORM_ADMIN';

-- Make networkId optional for platform-level events
ALTER TABLE "audit_logs" ALTER COLUMN "network_id" DROP NOT NULL;

-- Add index on actorId for faster lookups by user
CREATE INDEX IF NOT EXISTS "audit_logs_actor_id_idx" ON "audit_logs"("actor_id");
